version: '3.8'
services:
  db:
    image: $DB_IMAGE:$DB_VERSION
    container_name: phenpostgres
    restart: unless-stopped
    ports:
        - "5430:5432"
    environment:
        - POSTGRES_USER=$DB_USER
        - POSTGRES_PASSWORD=$DB_PASSWORD
        - POSTGRES_DB=postgres
    networks:
        - phen-network
    volumes:
        - postgres:$DB_CONTAINER_PATH
  backendphen:
    build:
        context: ../../
        dockerfile:  ./phenapp/docker_db/phen.Dockerfile
    depends_on:
        - db
    container_name: nodephen
    restart: unless-stopped
    networks:
        - phen-network
    ports:
        - '4000:4000'
networks:
    phen-network:
        driver: bridge
volumes:
  postgres:

   
