version: '3.3'
services:
  db:
    image: $DB_IMAGE:$DB_VERSION
    container_name: phenpostgres
    restart: unless-stopped
    ports:
        - "5430:5432"
    environment:
        - POSTGRES_USER=$DB_USER
        - POSTGRES_PASSWORD=$DB_PASSWORD
        - POSTGRES_DB=postgres
    volumes:
        - postgres:$DB_CONTAINER_PATH
volumes:
  postgres: