#!/bin/bash
# Config and Install Postgres-Docker
# Author: lczambra: mayo-2021


# Set local datetime
if [ -f /etc/localtime/ ]; then
  cp /usr/share/zoneinfo/America/Guayaquil /etc/localtime
fi

dt=$(date '+%d-%m-%Y--%H-%M-%S')

# Install docker - docker-compose
. /etc/os-release
SO=$ID

# Install docker and docker-compose (Centos)
if [ "$SO" = "centos" ]; then
     echo "(tput setaf 4)***************** Updating System ... ************************************************$(tput setaf 3)"
     yum -y update
     echo "(tput setaf 4)***************** Instaling project dependencies ... ***************************************$(tput setaf 3)"
     yum install -y yum-utils device-mapper-persistent-data lvm2 --no-install-recommends
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     echo "(tput setaf 4)***************** Instaling Docker ... ******************************************$(tput setaf 3)"
     yum install -y docker-ce
     usermod -aG docker $(whoami)
     gpasswd -a ${USER} docker
     systemctl enable docker.service
     systemctl start docker.service
     yum install -y epel-release
     echo "(tput setaf 4)*************** Instaling Python-pip ... ****************************************$(tput setaf 3)"
     yum install -y python-pip --no-install-recommends
     echo "(tput setaf 4)************** Instaling DockerCompose .... *************************************$(tput setaf 3)"
     pip install docker-compose --no-install-recommends
     echo "(tput setaf 4)************* Upgrading Python ... *********************************************$(tput setaf 3)"
     yum -y upgrade python --no-install-recommends
     docker version
     docker-compose version
     yum -y install make
fi

# Install docker and docker-compose (Ubuntu)
if [ "$SO" = "ubuntu" ]; then
apt-get install make
  if [ ! -e /usr/bin/docker ] || [ ! -e /usr/bin/docker-compose ]; then
        echo "$(tput setaf 4)***************** Updating System ....  ************************************************$(tput setaf 3)"
        apt-get update
                if [ ! -e /usr/bin/docker ]; then
			echo "$(tput setaf 4)***************** Instaling DOCKER ... ******************************************$(tput setaf 3)"
                        apt-get -y install docker.io --no-install-recommends
                        groupadd docker
                        usermod -aG docker $USER
                        newgrp docker
                fi
                if [ ! -e /usr/bin/docker-compose ]; then
                        echo "$(tput setaf 4)***************** Instaling DockerCompose ... ******************************************$(tput setaf 3)"
			apt-get -y install docker-compose --no-install-recommends
                fi
  fi
fi


make build
# Generate environment file
echo "$(tput setaf 4)***************** Building env .... *********************$(tput setaf 3)"
sh ./script/env

echo "$(tput setaf 4)****************** Up services .... *******************************$(tput setaf 3)"
make compose
make logs