compose:
	docker-compose up --build -d
stop:
	docker-compose stop
start:
	docker-compose start
clear:
	make stop
	docker-compose rm -f && docker volume prune -f
prune:
	docker system prune -af
logs:
	docker-compose logs -f --tail 20
restart:
	docker restart nodephen/ && docker logs -f nodephen/ --tail $(line)